
name: Test & lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  spec:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} w/ ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
        gemfile:
          - tzinfo_2_0
          - active_support_6_1
          - active_support_7_0
          - active_support_7_1
        exclude:
          - ruby: "2.6"
            gemfile: active_support_7_0
          - ruby: "2.6"
            gemfile: active_support_7_1
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_PATH: "gemfiles/vendor/bundle"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - uses: actions/cache@v3
        with:
          # NOTE: Bundler expands the path relative to the gemfile, not the
          # current directory.
          path: ./gemfiles/vendor/bundle
          key: bundled-gems-${{ runner.os }}-ruby-${{ matrix.ruby }}-${{ matrix.gemfile }}-${{ hashFiles( 'gemfiles/*.lock' ) }}
          restore-keys: |
            bundled-gems-${{ runner.os }}-ruby-${{ matrix.ruby }}-${{ matrix.gemfile }}-
            bundled-gems-${{ runner.os }}-ruby-${{ matrix.ruby }}-
      - name: Run tests
        run: bundle exec rspec
